name: Integration

env:
  go-version: "1.25"
  vuln-version: "v1.1.4"
  lint-version: "v2.6.1"

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - master
      - main
      - '**'

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  vulncheck:
    name: vulncheck
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: set up go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ env.go-version }}
          cache: true
      - name: install
        run: go install golang.org/x/vuln/cmd/govulncheck@${{ env.vuln-version }}
      - name: govulncheck
        run: make vulcheck

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ env.go-version }}
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: ${{ env.lint-version }}
          args: --timeout 10m
          only-new-issues: true

  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Start compose
        run: |
          make dev_up_ci
          sleep 10
      - name: Cache Go modules
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set up go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ env.go-version }}
          cache: true
      - name: Run tests
        run: CI_RUN="true" make test
      - name: Measure test coverage
        run: make coverage
